"""create order table

Revision ID: V4
Revises: V3
Create Date: 2025-01-06 09:19:12.762033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'V4'
down_revision: Union[str, None] = 'V3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('order_details', sa.String(length=500), nullable=False),
    sa.Column('cart_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_name', sa.String(length=250), nullable=True),
    sa.Column('user_phone', sa.String(length=100), nullable=True),
    sa.Column('order_date', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.alter_column('menu', 'name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.drop_table('customer_order')
    # ### end Alembic commands ###
