"""update order table

Revision ID: V5
Revises: V4
Create Date: 2025-01-06 21:41:29.295319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'V5'
down_revision: Union[str, None] = 'V4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order', sa.Column('payment_mode', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_order', 'payment_mode')
    # ### end Alembic commands ###
