"""update vendor_expenses table

Revision ID: V6
Revises: V5
Create Date: 2026-03-07 22:00:00.000000

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'V6'
down_revision: Union[str, None] = 'V5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'vendor_expenses',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('vendor', sa.String(length=100), nullable=False),
        sa.Column('material', sa.String(length=100), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('payment_mode', sa.String(length=20), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False, default=datetime.utcnow),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_expenses')
    # ### end Alembic commands ###
